decorations = "None"
import = ["/home/folke/projects/tokyonight.nvim/extras/alacritty/tokyonight_storm.yml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 11.0

[font.bold]
family = "Fira Code Bold Nerd Font Complete"

[font.bold_italic]
family = "Victor Mono Bold Italic Nerd Font Complete"

[font.italic]
family = "Victor Mono Medium Italic Nerd Font Complete"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[window.padding]
x = 10
y = 10
